// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expeditions/:slug": {
    params: {
      "slug": string;
    };
  };
  "/editions": {
    params: {};
  };
  "/legacy": {
    params: {};
  };
  "/consultation": {
    params: {};
  };
  "/yeti-infrastructure": {
    params: {};
  };
  "/newsletter": {
    params: {};
  };
  "/news-and-blogs": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/design-your-expedition": {
    params: {};
  };
  "/api/upload-cv": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/safety": {
    params: {};
  };
  "/heritage-and-achievements": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expeditions/:slug" | "/editions" | "/legacy" | "/consultation" | "/yeti-infrastructure" | "/newsletter" | "/news-and-blogs" | "/faq" | "/design-your-expedition" | "/api/upload-cv" | "/sitemap.xml" | "/robots.txt" | "/safety" | "/heritage-and-achievements";
  };
  "./app/pages/Home.tsx": {
    id: "app/pages/Home";
    page: "/";
  };
  "./app/pages/ExpeditionDossier.tsx": {
    id: "app/pages/ExpeditionDossier";
    page: "/expeditions/:slug";
  };
  "./app/pages/EditionsPage.tsx": {
    id: "app/pages/EditionsPage";
    page: "/editions";
  };
  "./app/pages/LegacyPage.tsx": {
    id: "app/pages/LegacyPage";
    page: "/legacy";
  };
  "./app/pages/EnquiryPage.tsx": {
    id: "app/pages/EnquiryPage";
    page: "/consultation";
  };
  "./app/pages/YetiInfrastructure.tsx": {
    id: "app/pages/YetiInfrastructure";
    page: "/yeti-infrastructure";
  };
  "./app/pages/NewsletterPage.tsx": {
    id: "app/pages/NewsletterPage";
    page: "/newsletter";
  };
  "./app/pages/NewsAndBlogsPage.tsx": {
    id: "app/pages/NewsAndBlogsPage";
    page: "/news-and-blogs";
  };
  "./app/pages/MainFAQ.tsx": {
    id: "app/pages/MainFAQ";
    page: "/faq";
  };
  "./app/pages/DesignPage.tsx": {
    id: "app/pages/DesignPage";
    page: "/design-your-expedition";
  };
  "./app/api/upload-cv.ts": {
    id: "app/api/upload-cv";
    page: "/api/upload-cv";
  };
  "./app/api/sitemap.xml.ts": {
    id: "app/api/sitemap.xml";
    page: "/sitemap.xml";
  };
  "./app/api/robots.txt.ts": {
    id: "app/api/robots.txt";
    page: "/robots.txt";
  };
  "./app/pages/SafetyPage.tsx": {
    id: "app/pages/SafetyPage";
    page: "/safety";
  };
  "./app/pages/HeritageAndAchievementsPage.tsx": {
    id: "app/pages/HeritageAndAchievementsPage";
    page: "/heritage-and-achievements";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "app/pages/Home": typeof import("./src/./app/pages/Home.tsx");
  "app/pages/ExpeditionDossier": typeof import("./src/./app/pages/ExpeditionDossier.tsx");
  "app/pages/EditionsPage": typeof import("./src/./app/pages/EditionsPage.tsx");
  "app/pages/LegacyPage": typeof import("./src/./app/pages/LegacyPage.tsx");
  "app/pages/EnquiryPage": typeof import("./src/./app/pages/EnquiryPage.tsx");
  "app/pages/YetiInfrastructure": typeof import("./src/./app/pages/YetiInfrastructure.tsx");
  "app/pages/NewsletterPage": typeof import("./src/./app/pages/NewsletterPage.tsx");
  "app/pages/NewsAndBlogsPage": typeof import("./src/./app/pages/NewsAndBlogsPage.tsx");
  "app/pages/MainFAQ": typeof import("./src/./app/pages/MainFAQ.tsx");
  "app/pages/DesignPage": typeof import("./src/./app/pages/DesignPage.tsx");
  "app/api/upload-cv": typeof import("./src/./app/api/upload-cv.ts");
  "app/api/sitemap.xml": typeof import("./src/./app/api/sitemap.xml.ts");
  "app/api/robots.txt": typeof import("./src/./app/api/robots.txt.ts");
  "app/pages/SafetyPage": typeof import("./src/./app/pages/SafetyPage.tsx");
  "app/pages/HeritageAndAchievementsPage": typeof import("./src/./app/pages/HeritageAndAchievementsPage.tsx");
};