// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/everest": {
    params: {};
  };
  "/expeditions/:slug": {
    params: {
      "slug": string;
    };
  };
  "/atlas": {
    params: {};
  };
  "/editions": {
    params: {};
  };
  "/legacy": {
    params: {};
  };
  "/team": {
    params: {};
  };
  "/consultation": {
    params: {};
  };
  "/archive": {
    params: {};
  };
  "/yeti-infrastructure": {
    params: {};
  };
  "/7000m": {
    params: {};
  };
  "/private": {
    params: {};
  };
  "/field-notes": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/api/upload-cv": {
    params: {};
  };
  "/safety": {
    params: {};
  };
  "/heritage-and-achievements": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/everest" | "/expeditions/:slug" | "/atlas" | "/editions" | "/legacy" | "/team" | "/consultation" | "/archive" | "/yeti-infrastructure" | "/7000m" | "/private" | "/field-notes" | "/faq" | "/api/upload-cv" | "/safety" | "/heritage-and-achievements";
  };
  "./app/pages/Home.tsx": {
    id: "app/pages/Home";
    page: "/";
  };
  "./app/pages/Everest.tsx": {
    id: "app/pages/Everest";
    page: "/everest";
  };
  "./app/pages/ExpeditionDossier.tsx": {
    id: "app/pages/ExpeditionDossier";
    page: "/expeditions/:slug";
  };
  "./app/pages/AtlasPage.tsx": {
    id: "app/pages/AtlasPage";
    page: "/atlas";
  };
  "./app/pages/EditionsPage.tsx": {
    id: "app/pages/EditionsPage";
    page: "/editions";
  };
  "./app/pages/LegacyPage.tsx": {
    id: "app/pages/LegacyPage";
    page: "/legacy";
  };
  "./app/pages/TeamPage.tsx": {
    id: "app/pages/TeamPage";
    page: "/team";
  };
  "./app/pages/EnquiryPage.tsx": {
    id: "app/pages/EnquiryPage";
    page: "/consultation";
  };
  "./app/pages/ExpeditionArchive.tsx": {
    id: "app/pages/ExpeditionArchive";
    page: "/archive";
  };
  "./app/pages/YetiInfrastructure.tsx": {
    id: "app/pages/YetiInfrastructure";
    page: "/yeti-infrastructure";
  };
  "./app/pages/SevenThousandMeterPathway.tsx": {
    id: "app/pages/SevenThousandMeterPathway";
    page: "/7000m";
  };
  "./app/pages/PrivateExpeditions.tsx": {
    id: "app/pages/PrivateExpeditions";
    page: "/private";
  };
  "./app/pages/FieldNotes.tsx": {
    id: "app/pages/FieldNotes";
    page: "/field-notes";
  };
  "./app/pages/MainFAQ.tsx": {
    id: "app/pages/MainFAQ";
    page: "/faq";
  };
  "./app/api/upload-cv.ts": {
    id: "app/api/upload-cv";
    page: "/api/upload-cv";
  };
  "./app/pages/SafetyPage.tsx": {
    id: "app/pages/SafetyPage";
    page: "/safety";
  };
  "./app/pages/HeritageAndAchievementsPage.tsx": {
    id: "app/pages/HeritageAndAchievementsPage";
    page: "/heritage-and-achievements";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "app/pages/Home": typeof import("./src/./app/pages/Home.tsx");
  "app/pages/Everest": typeof import("./src/./app/pages/Everest.tsx");
  "app/pages/ExpeditionDossier": typeof import("./src/./app/pages/ExpeditionDossier.tsx");
  "app/pages/AtlasPage": typeof import("./src/./app/pages/AtlasPage.tsx");
  "app/pages/EditionsPage": typeof import("./src/./app/pages/EditionsPage.tsx");
  "app/pages/LegacyPage": typeof import("./src/./app/pages/LegacyPage.tsx");
  "app/pages/TeamPage": typeof import("./src/./app/pages/TeamPage.tsx");
  "app/pages/EnquiryPage": typeof import("./src/./app/pages/EnquiryPage.tsx");
  "app/pages/ExpeditionArchive": typeof import("./src/./app/pages/ExpeditionArchive.tsx");
  "app/pages/YetiInfrastructure": typeof import("./src/./app/pages/YetiInfrastructure.tsx");
  "app/pages/SevenThousandMeterPathway": typeof import("./src/./app/pages/SevenThousandMeterPathway.tsx");
  "app/pages/PrivateExpeditions": typeof import("./src/./app/pages/PrivateExpeditions.tsx");
  "app/pages/FieldNotes": typeof import("./src/./app/pages/FieldNotes.tsx");
  "app/pages/MainFAQ": typeof import("./src/./app/pages/MainFAQ.tsx");
  "app/api/upload-cv": typeof import("./src/./app/api/upload-cv.ts");
  "app/pages/SafetyPage": typeof import("./src/./app/pages/SafetyPage.tsx");
  "app/pages/HeritageAndAchievementsPage": typeof import("./src/./app/pages/HeritageAndAchievementsPage.tsx");
};