import { defineType, defineField } from 'sanity'

export default defineType({
  name: 'atlasPage',
  title: 'Atlas Page',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero' },
    { name: 'controls', title: 'Controls' },
    { name: 'comparison', title: 'Comparison' },
    { name: 'pathway', title: '7,000m Pathway' },
    { name: 'seasonalGuide', title: 'Seasonal Guide' },
  ],
  fields: [
    defineField({ name: 'heroHeadline', title: 'Headline', type: 'string', group: 'hero' }),
    defineField({ name: 'heroSubheading', title: 'Subheading', type: 'text', rows: 3, group: 'hero' }),
    defineField({ name: 'heroImage', title: 'Background Image', type: 'image', group: 'hero', options: { hotspot: true } }),
    defineField({ name: 'controlsEyebrow', title: 'Eyebrow', type: 'string', group: 'controls', description: 'e.g. 02 — ATLAS CONTROLS' }),
    defineField({ name: 'controlsSubline', title: 'Subline', type: 'string', group: 'controls', description: 'e.g. INDEXED BY THE THAMSERKU DESK (the expedition count is prepended automatically)' }),
    defineField({ name: 'comparisonEyebrow', title: 'Eyebrow', type: 'string', group: 'comparison', description: 'e.g. 04 — AT A GLANCE' }),
    defineField({ name: 'comparisonHeadline', title: 'Headline', type: 'string', group: 'comparison', description: 'e.g. Five mountains, read side by side.' }),
    defineField({ name: 'comparisonNote', title: 'Footer Note', type: 'text', rows: 2, group: 'comparison', description: 'Italic note shown below the comparison table' }),
    defineField({ name: 'pathwayEyebrow', title: 'Eyebrow', type: 'string', group: 'pathway', description: 'e.g. BEFORE THE 8,000M PEAKS — A QUALIFYING PATHWAY' }),
    defineField({ name: 'pathwayHeading', title: 'Heading', type: 'string', group: 'pathway' }),
    defineField({ name: 'pathwaySubheading', title: 'Subheading', type: 'string', group: 'pathway', description: 'Italic blue line beneath heading' }),
    defineField({ name: 'pathwayBody', title: 'Body', type: 'text', rows: 3, group: 'pathway' }),
    defineField({ name: 'pathwayCta1Label', title: 'CTA 1 Label', type: 'string', group: 'pathway' }),
    defineField({ name: 'pathwayCta1Href', title: 'CTA 1 Link', type: 'string', group: 'pathway', description: 'e.g. /consultation?intent=7000m' }),
    defineField({ name: 'pathwayCta2Label', title: 'CTA 2 Label', type: 'string', group: 'pathway' }),
    defineField({ name: 'pathwayCta2Href', title: 'CTA 2 Link', type: 'string', group: 'pathway', description: 'e.g. /7000m' }),
    defineField({ name: 'pathwayFootnote', title: 'Footnote', type: 'string', group: 'pathway' }),
    defineField({ name: 'seasonalGuideEyebrow', title: 'Eyebrow', type: 'string', group: 'seasonalGuide', description: 'e.g. 05 — SEASONAL GUIDE' }),
    defineField({ name: 'seasonalGuideHeadline', title: 'Headline', type: 'string', group: 'seasonalGuide' }),
    defineField({ name: 'springWindowLabel', title: 'Spring Window Label', type: 'string', group: 'seasonalGuide' }),
    defineField({ name: 'springWindowDescription', title: 'Spring Window Description', type: 'text', rows: 3, group: 'seasonalGuide' }),
    defineField({ name: 'autumnWindowLabel', title: 'Autumn Window Label', type: 'string', group: 'seasonalGuide' }),
    defineField({ name: 'autumnWindowDescription', title: 'Autumn Window Description', type: 'text', rows: 3, group: 'seasonalGuide' }),
    defineField({ name: 'offSeasonLabel', title: 'Off-Season Label', type: 'string', group: 'seasonalGuide' }),
    defineField({ name: 'offSeasonDescription', title: 'Off-Season Description', type: 'text', rows: 3, group: 'seasonalGuide' }),
  ],
  preview: {
    prepare: () => ({ title: 'Atlas Page' }),
  },
})
